# Your GitHub workflow file under .github/workflows/
name: Deploy docfx documentation

on:
  push:
    branches: ["main", "grid-based-inventory"]

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  setup-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
  # Compile Docs
  compile-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - run: dotnet tool update -g docfx
      - run: docfx docfx_project/docfx.json
      - run: mv docfx_project/_site _site/
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1



  # Deployment job
  deploy:
    environment:
      name: github-pages
      # url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [setup-pages, compile-docs]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1